# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NativeWithCocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Flutter',:podspec => 'Debug/Flutter.podspec'
  # Pods for NativeWithCocoapods

end
